# Generated by Django 6.0.2 on 2026-05-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_aadhaar_number_users_blood_group_and_more'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_user', to='webapp.school'),
        ),
    ]
