# Generated by Django 6.0.2 on 2026-05-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcontact',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_contact', to='webapp.school'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_registeration', to='webapp.school'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='classes',
            field=models.ManyToManyField(blank=True, to='webapp.subjects'),
        ),
    ]
