# Generated by Django 6.0.2 on 2026-05-17 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_schoolcontact_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubjects',
            name='max_marks',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='classsubjects',
            name='pass_marks',
            field=models.FloatField(default=35),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='max_marks',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='pass_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='board',
            field=models.CharField(blank=True, choices=[('STATE_BOARD', 'State_board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IB', 'International_baccalaureate'), ('IGCSE', 'IGCSE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='board',
            field=models.CharField(blank=True, choices=[('STATE_BOARD', 'State_board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IB', 'International_baccalaureate'), ('IGCSE', 'IGCSE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teachereducationdetails',
            name='pass_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='teacheremploymentdetails',
            name='allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacheremploymentdetails',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
