# Generated by Django 6.0.2 on 2026-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_classsubjects_max_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolteacher',
            name='is_assistant_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
