# Generated by Django 6.0.2 on 2026-05-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_schoolteacher_is_assistant_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubjects',
            name='subject_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_as_subject_class', to='webapp.schoolclass'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='assistant_teacher',
            field=models.ManyToManyField(related_name='classes_as_assistant_teacher', to='webapp.schoolteacher'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_class_teacher', to='webapp.schoolteacher'),
        ),
    ]
