# Generated by Django 6.0.2 on 2026-05-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_classsubjects_subject_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('BOTH', 'Both')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('school', 'code')},
        ),
    ]
