# Generated by Django 6.0.2 on 2026-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_subjects_code_alter_subjects_subject_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgroup',
            name='classes',
            field=models.ManyToManyField(blank=True, to='webapp.schoolclass'),
        ),
    ]
