# Generated by Django 6.0.2 on 2026-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_studentparentdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsadmissiondetails',
            name='admission_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
