# Generated by Django 6.0.2 on 2026-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_studentsadmissiondetails_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='students',
            name='previous_academic_years',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='academic_year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
    ]
