# Generated by Django 6.0.2 on 2026-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_school_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubjects',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classsubjects',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='subject_teacher', to='webapp.schoolteacher'),
        ),
    ]
