# Generated by Django 6.0.2 on 2026-07-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_classsubjects_teacher_classsubjects_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
    ]
