# Generated by Django 6.0.2 on 2026-07-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_exam_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
    ]
