# Generated by Django 6.0.2 on 2026-07-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_examschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='consolidated_mark',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_marks', to='webapp.mark'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('exam_schedule', 'consolidated_mark')},
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student_exam',
        ),
    ]
